package Challengesemester2024.domain.facility.floorPictureCluster.repository;

import Challengesemester2024.SpringSecurity.authentication.AuthenticatedEmailDTO;
import Challengesemester2024.domain.facility.floorPictureCluster.dto.GetFloorPictureClusterPKDto;
import Challengesemester2024.domain.facility.floorPicutre.model.FloorPicture;

public interface FloorPictureClusterRepositoryCustom {
    public GetFloorPictureClusterPKDto getFloorPicutreClusterPk(AuthenticatedEmailDTO authenticatedEmailDTO);
    public void updateFloorPictureList(GetFloorPictureClusterPKDto getFloorPictureClusterPKDto, FloorPicture floorPicture);
}
