package Challengesemester2024.domain.facility.floorPictureCluster.repository;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public class FloorPictureClusterRepositoryImpl implements FloorPictureClusterRepositoryCustom {
}
